# -*- coding: utf-8 -*-
"""Prompt 模板 — 统一记忆抽取、记忆生成。"""

from app.prompts.extraction import (
    EXTRACTION_SYSTEM_PROMPT,
    EXTRACTION_USER_TEMPLATE,
    EXTRACTION_OUTPUT_SCHEMA,
)
from app.prompts.memory_generation import (
    MEMORY_GENERATION_SYSTEM_PROMPT,
    MEMORY_GENERATION_USER_TEMPLATE,
    MEMORY_GENERATION_OUTPUT_SCHEMA,
)

__all__ = [
    "EXTRACTION_SYSTEM_PROMPT",
    "EXTRACTION_USER_TEMPLATE",
    "EXTRACTION_OUTPUT_SCHEMA",
    "MEMORY_GENERATION_SYSTEM_PROMPT",
    "MEMORY_GENERATION_USER_TEMPLATE",
    "MEMORY_GENERATION_OUTPUT_SCHEMA",
]
